cfn.yaml, src/main/scala/com/gu/sfl/controller/FetchArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveForLaterController.scala, src/main/scala/com/gu/sfl/lambda/LambdaApiGateway.scala, src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, src/main/scala/com/gu/sfl/model/model.scala, src/main/scala/com/gu/sfl/persisitence/SavedArticlesPersistence.scala, src/main/scala/com/gu/sfl/savedarticles/UpdateSavedArticles.scala, src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala, src/test/scala/com/gu/sfl/savedarticles/UpdateSavedArticlesSpec.scala
Fixes the json response to updating saved articles so that it matches that currently provided by id.guardianapis.com, We post to /syncedPrefs/me/savedArtices. we GET from /syncedPrefs/me and the generated json needs to reflect this, MY BAD
Also changes the response headers so that they match those currentty live.
=> wrap post response correctly

src/main/scala/com/gu/sfl/controller/FetchArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveForLaterController.scala, src/main/scala/com/gu/sfl/model/model.scala
This returns the same json as the previous service. Ie 
```{"errors":[{"message":"Access Denied","description":"Access Denied"}]}```
Ie here: https://github.com/guardian/identity/blob/master/identity-synced-prefs/src/main/scala/com/gu/identity/api/servlet/SyncedPrefsServlet.scala#L93
=> Fix user not found error

src/main/scala/com/gu/sfl/controller/SaveArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveForLaterController.scala, src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, src/main/scala/com/gu/sfl/util/StatusCodes.scala, src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala
Corrects the error response returned when the max number of articles is exceeded to:
{"errors":[{"message":"Payload too large","description":"The limit on number of saved articles is 1000"}]}
As per https://github.com/guardian/identity/blob/master/identity-model/src/main/scala/com/gu/identity/model/Errors.scala#L67
=> Max articles error

src/main/scala/com/gu/sfl/controller/FetchArticlesController.scala, src/main/scala/com/gu/sfl/model/model.scala, src/main/scala/com/gu/sfl/savedarticles/FetchSavedArticles.scala, src/test/scala/com/gu/sfl/savedarticles/FetchSavedcArticlesSpec.scala
This fixes the vast majority of the errors seen here - which are coming up as 5xx errors when the user has no articles save: 
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#dashboards:name=SaveForLater
Here we respond instead with a 200 and an empty response
=> return an empty ok response when the user has no saved articles

src/main/scala/com/gu/sfl/controller/FetchArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveForLaterController.scala, src/main/scala/com/gu/sfl/model/model.scala
Correctly formats all error responses so that they match those previously served by the identity api: The format should be: 
```{"status":"error", "errors":[{"message":"xMessage","description":"xDescription"}]}```
=> give error responses a status

src/main/scala/com/gu/sfl/controller/FetchArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveArticlesController.scala, src/main/scala/com/gu/sfl/controller/SaveForLaterController.scala, src/main/scala/com/gu/sfl/exception/SaveForLaterError.scala, src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, src/main/scala/com/gu/sfl/savedarticles/FetchSavedArticles.scala, src/main/scala/com/gu/sfl/savedarticles/UpdateSavedArticles.scala, src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala, src/test/scala/com/gu/sfl/savedarticles/FetchSavedcArticlesSpec.scala, src/test/scala/com/gu/sfl/savedarticles/UpdateSavedArticlesSpec.scala
Refactors from a Future[SavedArticles] model to a Future[Either[Error, SavedArticles] model in order to handle errors in a more robust scala like way. My bad, I did chapter 4 of the scala red book a few weeks ago and I should have known better
=> Refactor error handling

src/main/scala/com/gu/sfl/controller/SaveArticlesController.scala, src/main/scala/com/gu/sfl/exception/SaveForLaterError.scala, src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, src/main/scala/com/gu/sfl/model/model.scala, src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala, src/test/scala/com/gu/sfl/lib/deup.sc
Take the most recent 1000 recent when a user saves. 
@alexduf as discussed. I want to keep the logging in that for de-duping which means this isn't as clean as it might be. Once I'm a more confident that all is well I'll remove that and refactor
=> only persist the most recent 1000 articles

mobile-save-for-later/src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala
Don't repersist articles when their the same as the ones already saved. This reduce our dynamo costs. Hopefully.
Note: When the versions are different I'm leaving as is
=> do not persist saved articles that are identical to those already saved

mobile-save-for-later-user-deletion/conf/cfn.yaml
How did it ever work? It is working correctly, but this should probably be fixed
Tested on code
=> fix the hardcoded variable

common/src/main/scala/com/gu/sfl/model/model.scala, common/src/test/scala/com/gu/sfl/model/SavedArticlesTest.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/controller/SaveArticlesController.scala
Old ios apps supported null dates.
Those nulls may still be returned be passed to and fro as saves have percolated through app evolutions.
=> MSS-458: Support null dates

mobile-save-for-later-user-deletion/conf/cfn.yaml
When I finished this PR: https://github.com/guardian/mobile-purchases/pull/81 I realised the alarm on the SFL deletion queue would need fixing too
=> fix user deletion queue#

mobile-save-for-later/conf/cfn.yaml
Mainly to save on cost. Saving aren't crazy but that's 80% of our dynamo cost
=> Move dynamo table to on demand

mobile-save-for-later/conf/cfn.yaml
That was a terrible idea, cost is nearly double for that type of load when using the on demand...
Woups 🤦‍♂
=> Revert "Move dynamo table to on demand"

mobile-save-for-later-user-deletion/conf/cfn.yaml
Reverts guardian/mobile-save-for-later#37
It turns out we were fine all along. The [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html) says
> In these examples, the asterisk (*) is used as a placeholder for Everyone/Anonymous. You cannot use it as a wildcard to match part of a name or an ARN. We also strongly recommend that you do not use a wildcard in the Principal element in a role's trust policy unless you otherwise restrict access through a Condition element in the policy. Otherwise, any IAM user in any account can access the role.
=> Revert "Fix security hole"

.gitignore, mobile-save-for-later/src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala
This is to identify how often do devices synchronize from an out of date version.
This might inform us regarding some of the save for later problem as discussed with @amajeedm
=> Add log line to identify version differences

mobile-save-for-later/src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala
So we can spot how often we delete stuff from the database if the client comes with an outdated version.
=> Adding more info on the log line

mobile-save-for-later/src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/savedarticles/UpdateSavedArticles.scala
So that we can hopefully debug the service better.
The goal is to trace how many articles we currently have in the DB, and how many articles we received in the request.
=> More precise logging

mobile-save-for-later/conf/cfn.yaml
Currently the service relies on unreserved capacity.
This has reached the extent where the service is now taking more concurrent execution than the account limit.
I'm now limiting it to 100 concurrent executions (baseline is at around 15 concurrent execution under high load, with unexplained bursts above 3K)
=> Throttle to 100 concurrent executions

mobile-save-for-later/conf/cfn.yaml
- More reasonable reserved concurrency down to 50. Observed live is lower than 15 when table isn't saturated.
- Smaller timeout at the lambda level. No need to hold for so long, let's free the lambda eagerly to reduce concurrency.
- Increased provisioned read units to 110 to cope with the load.
- Lower the provisioned write units to 50 as we don't seem to be using it.
=> Greater capacity

mobile-save-for-later/conf/cfn.yaml
Add a cloudformation throttle alarm for save for later articles, and delete manually created alarms in cloudwatch.
Named:
`mobile-save-for-later-PROD-articles-ReadCapacityUnitsLimit-BasicAlarm`
`mobile-save-for-later-CODE-articles-ReadCapacityUnitsLimit-BasicAlarm`
@alexduf I should delete the `write` ones from the console too, presuming they have also manually been created?
`mobile-save-for-later-PROD-articles-WriteCapacityUnitsLimit-BasicAlarm`
`mobile-save-for-later-CODE-articles-WriteCapacityUnitsLimit-BasicAlarm`
=> Add a cloudformation throttle alarm for save for later articles

mobile-save-for-later/conf/cfn.yaml
We have recently noticed write throttle events for this table:
I've tried to guess a more appropriate threshold, based on [this advice](https://stackoverflow.com/a/17188893) and our current usage:
=> Increase provisioned write capacity

mobile-save-for-later/conf/cfn.yaml
Whilst following up on https://github.com/guardian/mobile-save-for-later/pull/45, I noticed that `mobile-save-for-later-PROD-articles-WriteCapacityUnitsLimit-BasicAlarm` remains in an alarm state even though we have not received a throttling event for many days.
I think this is because we are not treating missing data appropriately for these cases. This PR attempts to fix that problem so that the alarm can resolve itself (which means that it will be able to fire again if we experience more throttling problems in the future). I've also taken the opportunity to disable alarm actions in `CODE`.
=> Fix alarm resolution and disable CODE alarms

mobile-save-for-later/conf/cfn.yaml
We should consider trialling the pay per request for our dynamo DB (for a week) and then we can estimate how much on average this would cost us a year.
This was tried before by Alex: https://github.com/guardian/mobile-save-for-later/pull/35 and swiftly rolled back because of spikes in costs, but it might work out cheaper in the long run than an engineer having to respond and react quickly to spikes to the service during high traffic news moments (i.e the US election)
We can monitor and then assess if this is the right approach or if we should try auto scaling as a longer term solution: https://github.com/guardian/mobile-save-for-later/pull/49
If the costs don't spike too much and become too expensive.
=> LIVE-1068: Change DyanamoDB to pay per request

mobile-save-for-later/conf/cfn.yaml
Reverts guardian/mobile-save-for-later#51
This is after a period of monitoring the effects of how much this costs estimated per year.
=> Revert "LIVE-1068: Change DyanamoDB to pay per request"

mobile-save-for-later/conf/cfn.yaml
Reverts guardian/mobile-save-for-later#52
We have noticed no significant increase in costs, which doesn't compare to a previous experiment. We have decided to lengthen the monitoring time to 1 month to get a fuller picture. We can then decide from there the action we take
=> Revert "Revert "LIVE-1068: Change DyanamoDB to pay per request""

mobile-save-for-later/conf/cfn.yaml
Reverts guardian/mobile-save-for-later#53
We have now tested the on demand pricing for a week, we can make an informed decision for what action we take, whether to keep with that or to put time in to producing auto scaling for the table. 
The cloudformation has been changed manually, this is to keep our repos up to date.
=> Revert LIVE-1068: Change DyanamoDB to pay per request

mobile-save-for-later-user-deletion/riff-raff.yaml, mobile-save-for-later/conf/cfn.yaml, mobile-save-for-later/riff-raff.yaml
Add CloudFormation deployment so it keeps our stacks up to date in version control. This PR also adds a deletion policy to mitigate accidental deletions of tables.
=> Add CloudFormation to our deployment

project/dependencies.scala, project/plugins.sbt
Update log4j dependency to fix security vulnerability - see [doc](https://docs.google.com/document/d/1nVKsXiEXLviHOMY1iQEoyacvN93_SYCQwsOFfaP-dxo)
It also adds a dependency graph plugin so we can run the command `sbt dependencyBrowseTree` which a handy way to quickly view our dependency tree in a browser: https://github.com/sbt/sbt-dependency-graph
Ran tests locally
=> update log4j dependency to fix security vulnerability

project/dependencies.scala
Updates aws-lambda-java-log4j2 to the latest version to help fix security vulnerability
=> Update aws-lambda-java-log4j2 to fix security vulnerability

mobile-save-for-later/src/main/scala/com/gu/sfl/identity/IdentityService.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/identity/IdentityServiceSpec.scala
Thanks to (Peter Colley) 
Authorise app requests using identity user identifiers endpoint to avoid hitting okta rate limit quotas.
user/me/identifiers does not hit okta endpoints, so does not incur rate limit cost
=> Use a new identity endpoint and do not log users out on 5XX code

cdk/bin/cdk.ts, cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, cdk/lib/mobile-save-for-later.ts, mobile-save-for-later/conf/cfn.yaml
**N.B. this PR depends on https://github.com/guardian/mobile-save-for-later/pull/64 and https://github.com/guardian/mobile-save-for-later/pull/65.**
We are migrating the `mobile-save-for-later` service from CloudFormation to `@guardian/cdk`. The migration will involve 5 PRs:
1. Add `@guardian/cdk` to repository; update CI & deployment wiring accordingly (https://github.com/guardian/mobile-save-for-later/pull/64)
2. Provision a new version of the infrastructure using `@guardian/cdk` (https://github.com/guardian/mobile-save-for-later/pull/65)
3. **Move DNS configuration from CloudFormation into `@guardian/cdk` (but continue routing requests to old infrastructure) [this PR]**
4. Update DNS configuration (start routing requests to new infrastructure) …
=> Move domain name configuration from CFN to cdk

mobile-save-for-later/src/main/scala/com/gu/sfl/lambda/LambdaApiGateway.scala
We want to send some artificial traffic to the cdk-version of this service before merging https://github.com/guardian/mobile-save-for-later/pull/67, to ensure that API Gateway/Lambda is not completely cold/scaled down.
However, for these lambdas to work successfully requests must contain a valid Identity token. If we send artificial traffic without these tokens the lambdas will throw errors, which will make it harder to interpret the [dashboard](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#dashboards:name=SaveForLater) when we're monitoring the migration. We only need the lambdas to start up to scale up the service, so this simple change allows the lambdas to complete successfully (without doing any useful work) if a special query param is set: …
=> Allow lambdas to be invoked without interacting with downstream services

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, cdk/lib/mobile-save-for-later.ts
**N.B. this PR depends on https://github.com/guardian/mobile-save-for-later/pull/64, https://github.com/guardian/mobile-save-for-later/pull/65 and https://github.com/guardian/mobile-save-for-later/pull/66.**
We are migrating the `mobile-save-for-later` service from CloudFormation to `@guardian/cdk`. The migration will involve 5 PRs:
1. Add `@guardian/cdk` to repository; update CI & deployment wiring accordingly (https://github.com/guardian/mobile-save-for-later/pull/64)
2. Provision a new version of the infrastructure using `@guardian/cdk` (https://github.com/guardian/mobile-save-for-later/pull/65)
3. Move DNS configuration from CloudFormation into `@guardian/cdk` (but continue routing requests to old infrastructure) (https://github.com/guardian/mobile-save-for-later/pull/66)
4. **Update …
=> Route all traffic to the cdk-defined infrastructure

cdk/bin/cdk.ts, cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap
**tl;dr** 
This PR allows the Lambda which fetches saved articles to scale more liberally in order to avoid unreliable deployments.
**Longer version**
AWS Lambda provides [a couple of different ways of controlling concurrency](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html). In the Mobile account, it is common to use reserved concurrency.
> Reserving concurrency has the following effects.
> 
> **Other functions can't prevent your function from scaling** – All of your account's functions in the same Region without reserved concurrency share the pool of unreserved concurrency. Without reserved concurrency, other functions can use up all of the available concurrency. This prevents your function from scaling up when needed.
> 
> **Your function can't scale out of …
=> Adjust reserved concurrency limit for fetch Lambda

cdk/bin/cdk.ts, cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap
https://github.com/guardian/mobile-save-for-later/pull/71 was an improvement, but unfortunately it was not sufficient to avoid throttling during deployment:
There were 85 throttles during the last deployment, so hopefully this amended limit will be sufficient without taking too much capacity from other services 🤞
=> Adjust reserved concurrency limit for fetch Lambda (again)

mobile-save-for-later/src/main/scala/com/gu/sfl/lambda/LambdaApiGateway.scala
guardian/mobile-save-for-later#70 was only necessary to facilitate the migration to GuCDK. That work is now complete, so  guardian/mobile-save-for-later#70 can be reverted.
=> Revert "Allow lambdas to be invoked without interacting with downstream services"

cdk/bin/cdk.ts, cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, cdk/lib/mobile-save-for-later.ts, mobile-save-for-later/conf/cfn.yaml
Adds some configuration to the CDK template, to allow monitoring for 5XX errors. Our read and write throttle alarms are triggered after 1 data point so I thought it would be good to keep to this pattern, and 1% error rate. 1 minute was also the pattern used in the throttle events so have matched with that, but i am open to suggestions.
As commented in this PR: https://github.com/guardian/mobile-save-for-later/pull/65#discussion_r885325721 - I think this means we can just have 5XX error monitoring and not migrate across alarms for throttling. So have removed them from the YAML template.
We successfully get notified about errors in our save for later service
=> LIVE-4204: Add 5xx monitoring to the save for later API

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, mobile-save-for-later/conf/cfn.yaml
Temporarily increase our table read capacity to hopefully ease traffic spikes on the save for later service.
- Bump the reads from 200 to 400
- 5XX error alarms ease off
=> Increase capacity for table reads

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, mobile-save-for-later/conf/cfn.yaml
Now the news of the Queens death has calmed we can reduce the read capacity of the save for later table back to 200.
=> Reduce table read capacity back to 200

build.sbt, cdk/package-lock.json, project/dependencies.scala
This PR bumps the following dependencies to fix the snyk vulnerabilities and one dependabot alert:
1) Jackson library 
2) okhttp library
3) parse-url 
We passed all the unit tests.
=> Bump okhttp jackson

mobile-save-for-later-user-deletion/riff-raff.yaml, mobile-save-for-later/riff-raff.yaml
From DevX: "Our [recommendations](https://github.com/guardian/recommendations/blob/main/github.md#repository-contents) for repository content suggests not committing S3 bucket names into public repositories."
We can update the riff raff config to remove the s3 bucket name by using the `bucketSsmLookup` property. Given that the deploy bucket already matches the value in `/account/services/artifact.bucket` we don't need to specify an additional ssm param for the bucket name. 
Additionally, `bucketSsmLookup` now defaults to `true`, so this isn't needed either, we can simply omit the `bucket` parameter.
=> Remove bucket parameter from riff-raff config

mobile-save-for-later-user-deletion/conf/cfn.yaml
The last continuous deploys of the save-for-later-user-deletion stack have failed:
Looking at the corresponding resources we can see that the topic associated with the queue depth alarm has been deleted from the stack:
To enable the deploy to be successful it's suggested that we:
- remove all references to the now deleted alarm topics
- use instead the generic `mobile-server-side` alarm topic
This change will involve updating resources, it will need to be deployed via riff raff using the "Dangerous" update strategy.
After a successful deploy to CODE:
- manually disable the lambda trigger from messages landing on queue `UserIdDeleteQueue-CODE`
- manually put 11 messages onto the queue
Expect to receive an alert in the server alerts google space.
=> Fix failing user deletion deploy

.github/workflows/snyk.yml
Since we now own this repository, it makes sense to push Mobile Save For Later based vulnerability warnings to the Personalisation Snyk organisation instead of the mobile one. I also deleted some outdated comments.
I ran the Snyk github action manually based on this branch and the Mobile Save For Later repository appeared in the Personalisation Organisation, so this definitely works.
=> Send snyk vulnerabilities to Personalisation organisation

mobile-save-for-later/src/main/scala/com/gu/sfl/identity/IdentityService.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/lambda/FetchArticlesLambda.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/lambda/SaveArticlesLambda.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/identity/IdentityServiceSpec.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/lambda/AwsLambdaSpec.scala, project/dependencies.scala
This PR updates the Mobile S4L's `identity-auth-core` dependency from 4.7 to 4.12. The `identity-auth-core` update from 4.7 to 4.8 was a breaking change, hence the changes needed to the IdentityService and tests as a result of this library update.
1. Automated tests pass
2. Snyk test no longer highlights a high vulnerability
3. Deployed to CODE and hit the saved articles POST and GET endpoints successfully.
Mobile apps continue to work as expected and we reduce the vulnerability count by 1
-   [ ] [Colour contrast …
=> Update identity-auth-core dependency to 4.12

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, mobile-save-for-later/conf/cfn.yaml
This is the initial attempt to address the following frequent alarm:
High 5XX error % from mobile-save-for-later (ApiGateway) in PROD
Every instance of this alarm firing matches a spike in writes to the `mobile-save-for-later-PROD-articles` Dynamo table, with the provisioned capacity not able to meet the demand.
This initial PR simply bumps up the write capacity to cope with the daily demand. We'll run with this for a few days to check that the alarms fire less frequently, then look into an auto-scaling solution.
Check the AWS UI to verify the write capacity has increased to 125 as expected. Monitor `P&E/Apps/ServerAlerts` over the coming days to see how often the alarm is firing.
Fewer alarms firing.
This will increase costs for a few days, but it's a cheap monthly cost and hopefully …
=> Increase Mobile S4L Articles Dynamo Table write capacity to 125

mobile-save-for-later-user-deletion/conf/cfn.yaml
This might feel a bit like cheating, but ultimately this alert is being triggered every day, and almost always being ignored. In my experience of looking into these alerts over the last couple of months, there's never actually been an issue that's needed fixing. The current version of this alarm is therefore too noisy and misleading to be useful. It's contributing to alert fatigue.
I'd like to bump the number of undeleted users up to 100 which feels like it would actually represent a backlog of undeleted users that we should act upon. Hopefully this will have the desired impact of an Engineer actually responding to the alert. As a final point, this alert hasn't been modified since it was created in 2018, so we're overdue reviewing this and doing something different.
Deploy the change, …
=> Increase User Deletion Lambda Alarm Threshold up to 100 user IDs

mobile-save-for-later/src/main/scala/com/gu/sfl/identity/IdentityService.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/identity/IdentityServiceSpec.scala, project/dependencies.scala
Bumps Identity Auth Core up to 4.15. This resolves a high vulnerability in the brilliantly named `bouncycastle` transitive dependency which was updated in the 4.15 release.
https://app.snyk.io/org/guardian-personalisation/project/d34cef19-1d16-41e4-b369-1aa662c5305f#issue-SNYK-JAVA-ORGBOUNCYCASTLE-6084022
https://github.com/guardian/identity/releases/tag/v4.15
I deployed this branch to CODE, and ran Postman queries against the fetch and save endpoints. They worked as expected.
Snyk high vulnerability count reduces to by 1, and Mobile S4L continues to work in production as expected.
The Identity API had changed slightly so this was a tiny bit more work than just bumping up the version number, but the changes were trivial enough.
=> Bump identity core to 4.15 to resolve bouncycastle vulnerability

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, mobile-save-for-later/conf/cfn.yaml
This PR allows us to start backing up `mobile-save-for-later`'s DynamoDB table using https://github.com/guardian/aws-backup.
For more details on this project see [this doc](https://docs.google.com/document/d/11EZtuVHCnjavE9AYLroiuDUsMzbp2ulFBtj4VkyCKNc/edit) and this [audit](https://docs.google.com/spreadsheets/d/1gNh_yQ3GVo_dVAemgZfRZM_MaQxep6_x-hzrhvVBGHY/edit#gid=1523470588) that @guardian/devx-reliability have been working on with Heads of Engineering & EMs.
I think that snapshot testing is sufficient here. I will also check that backups are created after this change has been merged.
We will be able to recover (most) article data stored in this table in the unlikely event that it is ever deleted.
Yes, a number of risks related to performance, cost and privacy were considered. See …
=> Enable nightly backups for DynamoDB table

build.sbt, project/build.properties
See https://github.com/guardian/scala-steward-public-repos/pull/68 ... we're now running our Scala Steward workflow with Java 21 LTS, which means that all projects that want to have Scala Steward updates (like this one) need to be able to build under Java 21 (even if the projects are still _running_ in production on Java 8).
_(unfortunately the Scala Steward run failing affects everyone, see https://github.com/guardian/scala-steward-public-repos/issues/60 - so I've removed `mobile-save-for-later` from Scala Steward until this PR is merged)_
Being able to build with Java 21 [requires](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#jdk-21-compatibility-notes) using recent versions of Scala (2.12.18+) and sbt (1.9.0+).
=> Allow building under Java 21 LTS

common/src/main/scala/com/gu/sfl/persistence/SavedArticlesPersistence.scala, mobile-save-for-later-user-deletion/conf/cfn.yaml, mobile-save-for-later-user-deletion/src/main/scala/coml/gu/sfl/userdeletion/db/SflDynamoDb.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/lib/SavedArticlesMerger.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/lib/ArticleMergeSpecification.scala, project/dependencies.scala
This PR does the job of upgrading the scanamo and dynamo library ahead of a larger upgrade to Java11. 
Changes: 
- Amazon client from Async to Sync. 
This was to maintain the type signatures as the AsyncScanamo returns a Future, and this would introduce much larger code changes. I don't think there should be operational reasons that we would need an async client in this case. It would be good to confirm this point. 
- Removes the write method which calls dyanmo's put method, in favour of calling `update` for both create and update requests. 
This is because put item https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html does not return the latest version of data in the data store. However update item https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/AP …
=> Upgrade dynamo sync

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, cdk/package-lock.json, cdk/package.json
This upgrade the guardian cdk library and the aws cdk libs, ahead of an upgrade to [Java 21](https://github.com/guardian/mobile-save-for-later/pull/109) which is needed to be able to use the `JAVA_21` enum. 
This has been regression tested on CODE
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#u …
=> Upgrade cdk libs

project/dependencies.scala
This explicitly adds the jackson core library and updates to the latest version of jackson to address the vulnerability raised in Snyk:
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
=> Explicitly add jackson core

cdk/lib/__snapshots__/mobile-save-for-later.test.ts.snap, cdk/lib/mobile-save-for-later.ts
This upgrades the TLS version to the latest supported for API Gateway: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html#cfn-apigateway-domainname-securitypolicy
as we have been informed our current TLS cipher is insecure https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html 
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contras …
=> Upgrade the TLS

build.sbt, project/dependencies.scala
This upgrades the version of netty in response to a security notification: https://github.com/advisories/GHSA-4g8c-wm8x-jfhw
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
=> Explicity include netty handler

common/src/main/scala/com/gu/sfl/Logging.scala, mobile-save-for-later/src/main/scala/com/gu/sfl/lambda/AwsLambda.scala, mobile-save-for-later/src/test/scala/com/gu/sfl/lambda/AwsLambdaSpec.scala
This updates the exception logging to include the errors message in the first line of the log statement. When I needed to debug this service it was difficult to identify the exception logs with the where they were being throw because it appears on a separate line in the logs. 
See 
Adding the error message to the first log statement should make it easier to search on exceptions being thrown 
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
- …
=> Include error message in log statement
